export const data = [
  {
    id: 1,
    imgsrc: "images/clover.jpg",
    title: "Black Clover Movie",
    subtitle: "Sword Of The Wizard King: 2023",
    link: "",
  },
  {
    id: 2,
    imgsrc: "images/korra.jpg",
    title: "The Legend Of Korra",
    subtitle: "Season - 1",
    link: "",
  },
  {
    id: 3,
    imgsrc: "images/panda.jpg",
    title: "Kung Fu Panda",
    subtitle: "Movie- The Dragon Knight : 2022",
    link: "",
  },
  {
    id: 4,
    imgsrc: "images/one piece.jpg",
    title: "One Piece Movie",
    subtitle: "Film  :- RED",
    link: "",
  },
  {
    id: 5,
    imgsrc: "images/bleach.jpg",
    title: "Bleach",
    subtitle: "Thousand year of Bloodwar",
    link: "",
  },
  {
    id: 6,
    imgsrc: "images/narutonc.jpg",
    title: "Naruto",
    subtitle: "Classic Naruto series",
    link: "",
  },
  {
    id: 7,
    imgsrc: "images/dc.jpg",
    title: "Demon Slayer",
    subtitle: "Infinity Train Arc",
    link: "",
  },
  {
    id: 8,
    imgsrc: "images/myheroacademia.jpg",
    title: "My Hero Academia",
    subtitle: "Season :- 1",
    link: "",
  },
  {
    id: 9,
    imgsrc: "images/yourname.jpg",
    title: "Your Name",
    subtitle: "movie-2016 ",
    link: "",
  },
  {
    id: 10,
    imgsrc: "images/castlevania.jpg",
    title: "Castlevania",
    subtitle: "Season :- 1",
    link: "",
  },
  {
    id: 11,
    imgsrc: "images/blood of zeus.jpg",
    title: "Blood Of Zeus",
    subtitle: "All Episodes",
    link: "",
  },
  {
    id: 12,
    imgsrc: "images/arcane.jpg",
    title: "Arcane",
    subtitle: "Season :- 1",
    link: "",
  },
  {
    id: 13,
    imgsrc: "images/korra.jpg",
    title: "The Legend Of Korra",
    subtitle: "Season - 2",
    link: "",
  },
];
